export {
  addClientDietMealItem,
  archiveClientDietPlan,
  createClientDietMealAlternative,
  createClientDietMeal,
  createClientDietPlan,
  duplicateClientDietPlan,
  publishClientDietPlan,
  removeClientDietMeal,
  removeClientDietMealItem,
  saveClientDietNotes,
  sendClientDietPlan,
  updateClientDietMealItem,
  updateClientDietPlanTargets,
} from "./legacy";
