export {
  addClientWorkoutExercise,
  addClientWorkoutSet,
  applyClientWorkoutTemplate,
  combineClientWorkoutBiset,
  createClientWorkoutProgram,
  createClientWorkoutSession,
  deleteClientWorkoutSession,
  duplicateClientWorkoutProgram,
  publishClientWorkoutProgram,
  removeClientWorkoutExercise,
  removeClientWorkoutSet,
  reorderClientWorkoutExercises,
  saveClientWorkoutNotes,
  saveClientWorkoutTemplate,
  sendClientWorkoutProgram,
  uncombineClientWorkoutBiset,
  updateClientWorkoutExercise,
  updateClientWorkoutSession,
  updateClientWorkoutSet,
} from "./legacy";
